import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const AI_ENABLED = Boolean(
  process.env.AI_HOST && process.env.AI_API_KEY && process.env.AI_MODEL_ID
)
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* expose runtime flag to client code */}
        <script
          dangerouslySetInnerHTML={{ __html: `window.__NEXT_PUBLIC_AI_ENABLED = ${AI_ENABLED ? 'true' : 'false'}` }}
        />
        {children}
      </body>
    </html>
  );
}
